step4: cyoa-step4.cpp pages-step4.hpp
	g++ -o cyoa-step4 -ggdb -std=gnu++98 cyoa-step4.cpp
step3: cyoa-step3.cpp pages.hpp
	g++ -o cyoa-step3 -ggdb -std=gnu++98 cyoa-step3.cpp
step2: cyoa-step2.cpp pages.hpp
	g++ -o cyoa-step2 -ggdb3 -std=gnu++98 cyoa-step2.cpp
step1:cyoa-step1.cpp pages.hpp
	g++ -o cyoa-step1 -ggdb3 -std=gnu++98 cyoa-step1.cpp
